version: '3'

services:

  bot:
    image: bot
    container_name: bot
    depends_on:
      - db
    volumes:
      - .:/usr/src/bot
    command: python3 app.py config.yml

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata: null
